project:
  type: website

website:
  title: "Candice Koolhaas"
  navbar:
    left:
      - href: /about
        text: About
      - href: /projects
        text: Projects
      - href: /contact
        text: Contact





