project:
  type: website

website:
  title: "Candice Koolhaas"
  navbar:
    left:
      - href: /index
        text: Home
      - href: /about
        text: About
      - href: /contact
        text: Contact





